---
#Copy Public Key

- name: Fail if requirement package does not exist
  command: rpm -q sshpass
  register: sshpass_pkg_exist
  failed_when: sshpass_pkg_exist.rc == 1
  
- name: Check params(can use only 1 params - target_vm, target_vms)
  fail:
    msg: "You can use only one of these params: target_vm, target_vms"
  when: target_vm is defined and target_vms is defined 
        
- name: Check if SSH public key exist
  stat:
    path: "{{ ssh_public_key }}"
  register: ssh_public_key_exist
  failed_when: not ssh_public_key_exist.stat.exists 

- name: Copy SSH public key to target_vm
  block:
   - name: Delete hosts from known_hosts
     lineinfile:
       path: ~/.ssh/known_hosts
       state: absent
       regexp: "{{ target_vm }}"
     
   - name: Copy SSH public key to target_vm
     shell: "sshpass -p {{target_vm_pw}} ssh-copy-id -o StrictHostKeyChecking=no -i {{ssh_public_key}} {{target_vm_id}}@{{target_vm}}; sleep 1"
  delegate_to: localhost 
  when: target_vm is defined 

- name: Copy SSH public key to target_vms
  block:
   - name: Delete hosts from known_hosts
     lineinfile:
       path: ~/.ssh/known_hosts
       state: absent
       regexp: "{{item}}"
     with_items:
       - "{{ target_vms }}"

   - name: Copy SSH public key to target_vms
     shell: "sshpass -p {{target_vm_pw}} ssh-copy-id -o StrictHostKeyChecking=no -i {{ssh_public_key}} {{target_vm_id}}@{{item}}; sleep 1"
     with_items:
     - "{{ target_vms }}"  
  delegate_to: localhost
  when: target_vms is defined 


